apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: careersim
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  JWT_SECRET: "SSSALALLSDADKASDJKk339jvvnewij23212iodadasdggh//aesaaso2334ffdlla:ssddd"
  JWT_REFRESH_SECRET: "Lowwww--DDDDD-D:3322jdd99djksq-3^2esjj29&das999dkdjsd-sad9@@2888"
  SESSION_SECRET: "cklsiwik3929KS.asjs+1232jijxjJASDIJj99k2wke2laAD--DSDJJKL3S"
  SMTP_USER: ""
  SMTP_PASS: ""
  OPENAI_API_KEY: "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"
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  STRIPE_PUBLISHABLE_KEY: ""
  RAG_API_KEY: "dev-token-eb4b864605e"
  TRANSFORMERS_API_KEY: "dev-token-bdd297cb5b5"
  LANGGRAPH_DEPLOYMENT_URL: ""
  LANGGRAPH_API_KEY: ""
  LANGCHAIN_API_KEY: ""
  GRAPH_ASSISTANT_ID: ""


