apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: careersim

commonLabels:
  app.kubernetes.io/part-of: careersim

resources:
  - namespace.yaml
  - pvc-uploads.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
  - rag-deployment.yaml
  - rag-service.yaml
  - transformers-deployment.yaml
  - transformers-service.yaml


